variables:
- template: ../variables/common.yml

stages:
- stage: Build_Test
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: Build and test
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: Use .NET SDK
      inputs:
        packageType: sdk
        version: 10.0.x
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: $(solutionPath)

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) --no-restore
