variables:
  buildConfiguration: 'Release'
  solutionPath: 'HttpClientManager.sln'
  projectPath: 'HttpClientManager.csproj'
  packageArtifactName: 'nuget-drop'
  devNextBranch: 'main'
  artifactsFeedName: 'CaptiveInnovations'
  artifactsFeedUrl: 'https://pkgs.dev.azure.com/tcrowe0170/_packaging/CaptiveInnovations/nuget/v3/index.json'
  validationPipelineId: '15'
